config/routes.rb
Attendance::Application.routes.draw do
  devise_for :students

  match '/' => 'students#index'
  match '/attend' => 'students#attend'
  match '/send_geolocation' => 'students#send_geolocation'

end

app/models/attend.rb
class Attend < ActiveRecord::Base
  attr_accessible :student_id
  belongs_to :student
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :attends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/students_controller.rb
# -*- coding: utf-8 -*-
class StudentsController < ApplicationController
  def index
    @students = Student.all

    # collect dates
    @dates = @students.map { |s|
      s.attends.map { |a|
        a.created_at.to_date
      }
    }.flatten.sort.uniq


    # collect attendats on each date
    for d in @dates
      # extend date to have attendants variable
      class << d
        attr_accessor :attendants
      end
      d.attendants = []

      for s in @students
        for a in s.attends
          if a.created_at.to_date == d
            d.attendants << s
            break
          end
        end
      end
    end
  end

  def attend
    authenticate_student!
    session[:current_student_id] = current_student.id
  end
  def send_geolocation
    current_student = Student.find_by_id(session[:current_student_id])

    if current_student == nil
      render :json => "Sesja wygasła.", :status => 401
    elsif params[:latitude] == nil || params[:longitude] == nil
      render :json => "Nie znaleziono danych geolokacyjnych.", :status => 406
    elsif too_far(params[:latitude].to_f, params[:longitude].to_f)
      render :json => "Znajdujesz się zbyt daleko.", :status => 406
    elsif incorrect_time()
      render :json => "Zgłoszenie poza godziną zajęć.", :status => 406
    else
      
      Attend.new(:student_id => session[:current_student_id]).save

      head :ok
    end
  end

  private
  
  def too_far(lat, long)
    pwr = Geokit::LatLng.new(51.107779, 17.061975)
    you = Geokit::LatLng.new(lat, long)
    dist = you.distance_to(pwr, :units => :kms)

    logger.debug('Distance is ' + dist.to_s + ' kms.')

    dist > 1
  end

  def incorrect_time
    false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Attendance</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to('attendance-michal.herokuapp.com', '/')  %>

<% if student_signed_in? %>
  <li>
  Jesteś zalogowany jako <%= current_student.email %>.
  <%= link_to('Wyloguj się.', destroy_student_session_path, :method => :delete) %>
  <%= link_to('Edytuj profil.', edit_student_registration_path) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Zaloguj się.', new_student_session_path)  %>
  <%= link_to('Zarejestruj się.', new_student_registration_path)  %>
  </li>
<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/students/attend.html.erb
<%= javascript_include_tag "attend" %>

<h1>Zgłoś swoją obecność</h1>

<input value="Zgłoś" type="button" onclick="attend()" />

<div id="attend_response"></div>

app/views/students/index.html.erb
<h1>Lista obecności</h1>

<table border="1">
  <tr>
    <td></td>
    <% for d in @dates %>
    <td><%= d.to_s %></td>
    <% end %>
  </tr>


  <% for s in @students %>
  <tr>
    <td><%= s.email %></td>
    <% for d in @dates %>
    <td>
      <center>
      <% if d.attendants.include?(s) %>
      obecny
      <% else %>
      -
      <% end %>
      </center>
    </td>
    <% end %>
  </tr>
  <% end %>
</table>

<br />

<%= link_to "Zgłoś swoją obecność", attend_path %>